### ISSUE TITLE
Fresh install on mavericks ... make error

### ISSUE THREAD

**Issue by bschlief** [boxen/puppet-python#26]
Prerequisites are all set: 
- command line tools downloaded via the apple developer site
- brew update is done
- brew doctor is okay

Getting an error about make with wrong number of arguments.

```
==> make frameworkinstallextras PYTHONAPPSDIR=/opt/boxen/homebrew/Cellar/python/2.7.3-boxen2/share/python
Error: wrong number of arguments (0 for 3)
```

To get around the error, I was able to manually `brew install python`, but I'd much prefer to use this module.  If anyone has had a similar experience or figured out how to work around it, I'd love to hear from you.

Thanks!

**Comment by jacobbednarz** [comment]
This issue is filed against an old version of OSX. I'm going to close it but please open a new one if you're experiencing this on a newer OS.
