### ISSUE TITLE
Status of this repo

### ISSUE THREAD

**Issue by Tristan-zimmerman** [boxen/puppet-python#32]
Hello, wondering what the status is on this repository. Currently using OSX 10.10, pip is unavailable and thus renders this module essentially useless. Several open pull requests are available and issues have been open for over a year without being fixed. I've noticed a few other modules, such as https://github.com/mloberg/puppet-python or https://github.com/hanjianwei/puppet-python that are atleast being maintained. 

Could someone educate me on the status of python in boxen, if it is still supported, or what the plan is for this? 

@dgoodlad @atmos - Any help much appreciated.

```
Error: Could not prefetch package provider 'pip': [nil, nil, nil, nil]
Error: /Package[fabric]: Could not evaluate: [nil, nil, nil, nil]
Notice: /Stage[main]/Python::Virtualenvwrapper/Python::Pip[virtualenvwrapper==3.7]/Exec[pip_install_virtualenvwrapper==3.7]/returns: Traceback (most recent call last):
Notice: /Stage[main]/Python::Virtualenvwrapper/Python::Pip[virtualenvwrapper==3.7]/Exec[pip_install_virtualenvwrapper==3.7]/returns:   File "/opt/boxen/homebrew/bin/pip", line 5, in <module>
Notice: /Stage[main]/Python::Virtualenvwrapper/Python::Pip[virtualenvwrapper==3.7]/Exec[pip_install_virtualenvwrapper==3.7]/returns:     from pkg_resources import load_entry_point
Notice: /Stage[main]/Python::Virtualenvwrapper/Python::Pip[virtualenvwrapper==3.7]/Exec[pip_install_virtualenvwrapper==3.7]/returns: ImportError: No module named pkg_resources
Error: /opt/boxen/homebrew/bin/pip install  virtualenvwrapper==3.7 returned 1 instead of one of [0]
Error: /Stage[main]/Python::Virtualenvwrapper/Python::Pip[virtualenvwrapper==3.7]/Exec[pip_install_virtualenvwrapper==3.7]/returns: change from notrun to 0 failed: /opt/boxen/homebrew/bin/pip install  virtualenvwrapper==3.7 returned 1 instead of one of [0]
```

The fabric error is coming from one of our internal modules, nothing strange there, except pip is unavailable. 

```
  package {'fabric':
    provider => 'pip',
  }
```

Thanks a lot, everyone.

**Comment by jarib** [comment]
I'm wondering the same thing. Looks pretty dead?

@Tristan-zimmerman What did you end up using for Python? The two other modules you linked hasn't had any commits in a while either.

**Comment by BillWeiss** [comment]
I've just started on boxen, and I had decent luck with https://github.com/mloberg/puppet-python.

**Comment by jacebrowning** [comment]
https://github.com/mloberg/puppet-python is working well for me.

**Comment by wadewilliams** [comment]
Worth mentioning https://github.com/boxen/boxen/issues/197

**Comment by jacobbednarz** [comment]
This repository is still being maintained. Unfortunately, I'm still working through a large-ish backlog of issues with the core modules and this is sitting behind those.

Let me know if you're interested in helping maintain this repository!
